---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: donahuenet # change to your domain
  namespace: traefik # add to traefik namespace so it can use it (you DO NOT need it in each app namespace!!!)
spec:
  secretName: donahuenet-tls # change to your secretname
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.donahuenet.xyz" # change to your domain
  dnsNames:
  - "*.donahuenet.xyz" # change to your domain
  - donahuenet.xyz # change to your domain
